<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEGzxK9W\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEGzxK9W/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEGzxK9W.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEGzxK9W\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEGzxK9W\App_KernelDevDebugContainer([
    'container.build_hash' => 'EGzxK9W',
    'container.build_id' => 'e7371bf3',
    'container.build_time' => 1620648249,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEGzxK9W');
