<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCTKxAuL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCTKxAuL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCTKxAuL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCTKxAuL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCTKxAuL\App_KernelDevDebugContainer([
    'container.build_hash' => 'CTKxAuL',
    'container.build_id' => 'c7bdd696',
    'container.build_time' => 1620544883,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCTKxAuL');
