<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWxe8Lqx\App_KernelDevContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWxe8Lqx/App_KernelDevContainer.php') {
    touch(__DIR__.'/ContainerWxe8Lqx.legacy');

    return;
}

if (!\class_exists(App_KernelDevContainer::class, false)) {
    \class_alias(\ContainerWxe8Lqx\App_KernelDevContainer::class, App_KernelDevContainer::class, false);
}

return new \ContainerWxe8Lqx\App_KernelDevContainer([
    'container.build_hash' => 'Wxe8Lqx',
    'container.build_id' => 'bf74309b',
    'container.build_time' => 1620292449,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWxe8Lqx');
