<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQTNftEN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQTNftEN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQTNftEN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQTNftEN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQTNftEN\App_KernelDevDebugContainer([
    'container.build_hash' => 'QTNftEN',
    'container.build_id' => '6d90ac87',
    'container.build_time' => 1620295667,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQTNftEN');
